apex-job/src/domain/objects/JobDescription__c/JobDescription__c.object-meta.xml
<CustomObject>
    <label>Job Description</label>
    <nameField>
        <label>Job Description Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Descriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

apex-job/src/engine/domain/objects/JobDescription__c/fields/MaxChunkSize__c.field-meta.xml
<CustomField>
    <fullName>MaxChunkSize__c</fullName>
    <defaultValue>-1</defaultValue>
    <label>Max Chunk Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

apex-job/src/domain/objects/JobRequest__c/JobRequest__c.object-meta.xml
<CustomObject>
    <description>Job Request</description>
    <label>Job Request</label>
    <nameField>
        <label>Job Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

apex-job/src/engine/domain/objects/JobRequest__c/fields/JobDescription__c.field-meta.xml
<CustomField>
    <fullName>JobDescription__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Description</label>
    <referenceTo>JobDescription__c</referenceTo>
    <relationshipLabel>Job Requests</relationshipLabel>
    <relationshipName>JobRequests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

apex-job/src/domain/classes/JobCandidate.cls
public class JobCandidate {
  private Integer calculatedChunkSize;
  private final JobDescription__c jobDescription;
  public final List<JobRequest__c> jobRequests;
  private final ChunkSizeCalculator chunkSizeCalculator;

  public JobCandidate(final List<JobRequest__c> jobRequests) {
    this(new ApexJobFactoryImpl().getChunkSizeCalculator(), jobRequests);
  }

  @TestVisible
  private JobCandidate(final ChunkSizeCalculator chunkSizeCalculator, final List<JobRequest__c> jobRequests) {
    this.jobRequests = jobRequests;
    this.jobDescription = jobRequests[0].JobDescription__r;
    this.chunkSizeCalculator = chunkSizeCalculator;
  }

  public Boolean isExecutable() {
    this.calculatedChunkSize = this.calculateChunkSize();
    return this.calculatedChunkSize > 0;
  }

  public JobExecutable getExecutableChunk() {
    final List<JobRequest__c> jobsChunk = new List<JobRequest__c>();
    for (Integer i = 0; i < this.calculatedChunkSize; ++i) {
      jobsChunk.add(this.jobRequests[i]);
    }
    return new JobExecutable(jobsChunk);
  }

  private Integer calculateChunkSize() {
    Integer chunkSize = this.jobDescription.MaxChunkSize__c.intValue();
    if (chunkSize == ApexJobConstant.UNKNOWN_MAX_CHUNK_SIZE) {
      return 1;
    }

    // Define max possible chunk size for current transaction
    chunkSize = this.chunkSizeCalculator.getMaxPossible(this.jobDescription);
    return Math.min(chunkSize, this.jobRequests.size());
  }
}