apex-job/src/domain/objects/JobDescription__c/JobDescription__c.object-meta.xml
<CustomObject>
    <label>Job Description</label>
    <nameField>
        <label>Job Description Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Descriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

apex-job/src/domain/objects/JobDescription__c/fields/isRecurrent__c.field-meta.xml
<CustomField>
    <fullName>isRecurrent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Recurrent</label>
    <type>Checkbox</type>
</CustomField>

apex-job/src/domain/objects/JobDescription__c/fields/MaxExecutionAttempt__c.field-meta.xml
<CustomField>
    <fullName>MaxExecutionAttempt__c</fullName>
    <defaultValue>-1</defaultValue>
    <label>Max Execution Attempt</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

apex-job/src/engine/domain/objects/JobDescription__c/fields/MinJobInterval__c.field-meta.xml
<CustomField>
    <fullName>MinJobInterval__c</fullName>
    <defaultValue>0</defaultValue>
    <description>In minutes</description>
    <label>Min Job Interval</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

apex-job/src/domain/objects/JobRequest__c/JobRequest__c.object-meta.xml
<CustomObject>
    <description>Job Request</description>
    <label>Job Request</label>
    <nameField>
        <label>Job Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

apex-job/src/domain/objects/JobRequest__c/fields/AttemptNumber__c.field-meta.xml
<CustomField>
    <fullName>AttemptNumber__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Attempt Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

apex-job/src/engine/domain/objects/JobRequest__c/fields/JobDescription__c.field-meta.xml
<CustomField>
    <fullName>JobDescription__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Description</label>
    <referenceTo>JobDescription__c</referenceTo>
    <relationshipLabel>Job Requests</relationshipLabel>
    <relationshipName>JobRequests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

apex-job/src/engine/domain/objects/JobRequest__c/fields/LastExecutionDateTime__c.field-meta.xml
<CustomField>
    <fullName>LastExecutionDateTime__c</fullName>
    <label>Last Execution Date Time</label>
    <type>DateTime</type>
</CustomField>

apex-job/src/engine/domain/objects/JobRequest__c/fields/LastExecutionMessage__c.field-meta.xml
<CustomField>
    <fullName>LastExecutionMessage__c</fullName>
    <label>Last Execution Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

apex-job/src/domain/objects/JobRequest__c/fields/NextExecutionDateTime__c.field-meta.xml
<CustomField>
    <fullName>NextExecutionDateTime__c</fullName>
    <label>Next Execution Date Time</label>
    <type>DateTime</type>
</CustomField>

apex-job/src/domain/objects/JobRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABORTED</fullName>
                <label>Aborted</label>
            </value>
            <value>
                <fullName>FAILURE</fullName>
                <label>Failure</label>
            </value>
            <value>
                <fullName>READY</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
                <label>Success</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

apex-job/src/domain/classes/JobExecuted.cls
public with sharing class JobExecuted {
  private static final List<ApexJobStatus> RETRYABLE_STATUS = new List<ApexJobStatus>{ ApexJobStatus.FAILURE, ApexJobStatus.KILLED };
  private static final String MAX_EXECUTION_ATTEMPT_REACHED = 'Max execution attempt reached';
  private static final Integer MAX_EXECUTION_ATTEMPT_NUMBER = 9999999;
  private static final Integer MAX_LONG_TEXT_LENGTH = 131072;

  @TestVisible
  private final ApexJobResult jobExecutionResult;
  private final ApexJobFactory factory;
  public final JobDescription__c jobDescription { get; private set; }
  public final List<JobRequest__c> jobRequests { get; private set; }

  public JobExecuted(final JobExecutable jobExecutable, final ApexJobResult jobExecutionResult) {
    this(new ApexJobFactoryImpl(), jobExecutable, jobExecutionResult);
  }

  @TestVisible
  private JobExecuted(final ApexJobFactory factory, final JobExecutable jobExecutable, final ApexJobResult jobExecutionResult) {
    this.factory = factory;
    this.jobDescription = jobExecutable.jobDescription;
    this.jobRequests = jobExecutable.jobRequests;
    this.jobExecutionResult = jobExecutionResult;
  }

  public void stageExecution() {
    this.stageJobRequestsChunkExecution();
    this.stageJobDescriptionExecution();
  }

  private void stageJobRequestsChunkExecution() {
    final Integer jobChunkNumber = this.jobRequests.size();
    final JobRequestExecutionStagingInfo stagingInfo = new JobRequestExecutionStagingInfo(this.jobExecutionResult, this.jobDescription);
    for (Integer i = 0; i < jobChunkNumber; ++i) {
      this.stageJobRequestExecution(this.jobRequests[i], stagingInfo);
    }
  }

  private void stageJobRequestExecution(final JobRequest__c job, final JobRequestExecutionStagingInfo stagingInfo) {
    job.LastExecutionDateTime__c = stagingInfo.executionTimestamp;
    job.AttemptNumber__c = Math.min((job.AttemptNumber__c ?? 0) + 1, MAX_EXECUTION_ATTEMPT_NUMBER);
    // Should abort
    if (stagingInfo.candidateAbortable && job.AttemptNumber__c >= this.jobDescription.MaxExecutionAttempt__c) {
      job.Status__c = ApexJobStatus.ABORTED.name();
      job.NextExecutionDateTime__c = null;
      List<String> lastExecutionMessage = new List<String>{ MAX_EXECUTION_ATTEMPT_REACHED };
      if (String.isNotBlank(stagingInfo.errorMessage)) {
        lastExecutionMessage.add(stagingInfo.errorMessage);
      }
      job.LastExecutionMessage__c = String.join(lastExecutionMessage, '\n').left(MAX_LONG_TEXT_LENGTH);
      // Failure or Killed
    } else if (stagingInfo.candidateStatusRetryable) {
      job.Status__c = this.jobExecutionResult.status.name();
      job.NextExecutionDateTime__c = stagingInfo.nextTry;
      job.LastExecutionMessage__c = stagingInfo.errorMessage;
      // Recurrent candidat
    } else if (stagingInfo.recurrentCandidat) {
      job.Status__c = ApexJobStatus.READY.name();
      job.NextExecutionDateTime__c = stagingInfo.nextTry;
      job.LastExecutionMessage__c = stagingInfo.errorMessage;
      // Abort or Success
    } else {
      job.Status__c = this.jobExecutionResult.status.name();
      job.NextExecutionDateTime__c = null;
      job.LastExecutionMessage__c = stagingInfo.errorMessage;
    }
  }

  private void stageJobDescriptionExecution() {
    final ConsumptionLearner consumptionLearner = this.factory.getConsumptionLearner(this.jobDescription);
    this.jobDescription.LastExecutionDateTime__c = System.now();
    if (this.jobExecutionResult.status == ApexJobStatus.FAILURE || this.jobExecutionResult.status == ApexJobStatus.ABORTED) {
      consumptionLearner.adjustFromFailure(this.jobExecutionResult.consumedLimits, this.jobRequests.size());
    } else if (this.jobExecutionResult.status == ApexJobStatus.SUCCESS) {
      consumptionLearner.adjustFromSuccess(this.jobExecutionResult.consumedLimits, this.jobRequests.size());
    } else if (this.jobExecutionResult.status == ApexJobStatus.KILLED) {
      consumptionLearner.adjustFromKill(this.jobRequests.size());
    }
  }

  private class JobRequestExecutionStagingInfo {
    public final Datetime executionTimestamp { get; private set; }
    public final Boolean candidateStatusRetryable { get; private set; }
    public final Boolean candidateAbortable { get; private set; }
    public final String errorMessage { get; private set; }
    public final Datetime nextTry { get; private set; }
    public final Boolean recurrentCandidat { get; private set; }

    public JobRequestExecutionStagingInfo(final ApexJobResult result, final JobDescription__c description) {
      this.executionTimestamp = System.now();
      this.candidateStatusRetryable = RETRYABLE_STATUS.contains(result.status);
      this.candidateAbortable = this.candidateStatusRetryable && description.MaxExecutionAttempt__c != -1;
      this.errorMessage = (result.error?.toString() ?? '').left(MAX_LONG_TEXT_LENGTH);
      final Integer minutes = (Integer) description.MinJobInterval__c ?? 0;
      this.nextTry = this.executionTimestamp.addMinutes(minutes);
      this.recurrentCandidat = description.isRecurrent__c == true;
    }
  }
}