apex-job/src/domain/objects/ApexJobConfig__c/ApexJobConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuration settings for the Apex Job async processor system</description>
    <label>Apex Job Config</label>
</CustomObject>

apex-job/src/domain/objects/ApexJobConfig__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Controls whether the Apex Job async processor system is enabled globally. When set to false, no new queueable jobs will be launched.</description>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

apex-job/src/domain/objects/JobDescription__c/JobDescription__c.object-meta.xml
<CustomObject>
    <label>Job Description</label>
    <nameField>
        <label>Job Description Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Descriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

apex-job/src/engine/domain/objects/JobDescription__c/fields/CalloutBaseConsumption__c.field-meta.xml
<CustomField>
    <fullName>CalloutBaseConsumption__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Expected number of callouts for this job type. Used for governor limit planning and tracking.</description>
    <label>Callout Consumption</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

apex-job/src/domain/objects/JobDescription__c/fields/ConsecutiveFailures__c.field-meta.xml
<CustomField>
    <fullName>ConsecutiveFailures__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of consecutive failed executions. Used to apply a panic factor reducing chunk size.</description>
    <label>Consecutive Failures</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

apex-job/src/engine/domain/objects/JobDescription__c/fields/MaxChunkSize__c.field-meta.xml
<CustomField>
    <fullName>MaxChunkSize__c</fullName>
    <defaultValue>-1</defaultValue>
    <label>Max Chunk Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

apex-job/src/domain/objects/JobDescription__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <defaultValue>-1</defaultValue>
    <description>Priority of the job description. The higher the priority, the more likely the job will be executed first.</description>
    <label>Priority</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

apex-job/src/domain/objects/JobDescription__c/fields/ProcessorName__c.field-meta.xml
<CustomField>
    <fullName>ProcessorName__c</fullName>
    <externalId>true</externalId>
    <label>Processor Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

apex-job/src/domain/objects/JobDescription__c/fields/SmallestFailingChunk__c.field-meta.xml
<CustomField>
    <fullName>SmallestFailingChunk__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Smallest chunk size that failed recently. If set, next chunk size will be at most half of this value.</description>
    <label>Smallest Failing Chunk</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

apex-job/src/domain/objects/JobDescription__c/fields/SuccessStreak__c.field-meta.xml
<CustomField>
    <fullName>SuccessStreak__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of consecutive successful executions. Used to control ramp-up factor.</description>
    <label>Success Streak</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

apex-job/src/domain/objects/JobRequest__c/JobRequest__c.object-meta.xml
<CustomObject>
    <description>Job Request</description>
    <label>Job Request</label>
    <nameField>
        <label>Job Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

apex-job/src/engine/domain/objects/JobRequest__c/fields/Argument__c.field-meta.xml
<CustomField>
    <fullName>Argument__c</fullName>
    <label>Argument</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

apex-job/src/domain/objects/JobRequest__c/fields/AttemptNumber__c.field-meta.xml
<CustomField>
    <fullName>AttemptNumber__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Attempt Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

apex-job/src/domain/objects/JobRequest__c/fields/ChunkRunTime__c.field-meta.xml
<CustomField>
    <fullName>ChunkRunTime__c</fullName>
    <description>Time spent in chunk executing this job in milliseconds</description>
    <label>Chunk Run Time (ms)</label>
    <type>Number</type>
    <precision>18</precision>
    <scale>0</scale>
</CustomField>

apex-job/src/domain/objects/JobRequest__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

apex-job/src/engine/domain/objects/JobRequest__c/fields/IsCandidat__c.field-meta.xml
<CustomField>
    <fullName>IsCandidat__c</fullName>
    <description>Define if the job can be executed</description>
    <formula>AND(
  Enabled__c
  ,JobDescription__r.Enabled__c
  ,OR(
    ISPICKVAL(Status__c, &quot;FAILURE&quot;),
    ISPICKVAL(Status__c, &quot;KILLED&quot;),
    ISPICKVAL(Status__c, &quot;READY&quot;)
  )
  ,OR( NOW() &gt;= NextExecutionDateTime__c , ISNULL(NextExecutionDateTime__c) )
  ,OR( ISNULL(AttemptNumber__c), JobDescription__r.MaxExecutionAttempt__c = -1, AttemptNumber__c &lt; JobDescription__r.MaxExecutionAttempt__c )
  ,OR(ISBLANK(JobDescription__r.AllowedDays__c) ,
    CASE(WEEKDAY(TODAY())
      ,1 , IF(INCLUDES(JobDescription__r.AllowedDays__c,&apos;1&apos; ),1,0)
      ,2 , IF(INCLUDES(JobDescription__r.AllowedDays__c,&apos;2&apos; ),1,0)
      ,3 , IF(INCLUDES(JobDescription__r.AllowedDays__c,&apos;3&apos; ),1,0)
      ,4 , IF(INCLUDES(JobDescription__r.AllowedDays__c,&apos;4&apos; ),1,0)
      ,5 , IF(INCLUDES(JobDescription__r.AllowedDays__c,&apos;5&apos; ),1,0)
      ,6 , IF(INCLUDES(JobDescription__r.AllowedDays__c,&apos;6&apos; ),1,0)
      ,7 , IF(INCLUDES(JobDescription__r.AllowedDays__c,&apos;7&apos; ),1,0)
      ,0) &gt; 0)
  ,OR (ISNULL(JobDescription__r.AllowedStartTime__c), TIMENOW() &gt;= JobDescription__r.AllowedStartTime__c)
  ,OR (ISNULL(JobDescription__r.AllowedEndTime__c), TIMENOW() &lt;= JobDescription__r.AllowedEndTime__c)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Candidat</label>
    <type>Checkbox</type>
</CustomField>

apex-job/src/engine/domain/objects/JobRequest__c/fields/JobDescription__c.field-meta.xml
<CustomField>
    <fullName>JobDescription__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Description</label>
    <referenceTo>JobDescription__c</referenceTo>
    <relationshipLabel>Job Requests</relationshipLabel>
    <relationshipName>JobRequests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

apex-job/src/engine/domain/objects/JobRequest__c/fields/LastExecutionDateTime__c.field-meta.xml
<CustomField>
    <fullName>LastExecutionDateTime__c</fullName>
    <label>Last Execution Date Time</label>
    <type>DateTime</type>
</CustomField>

apex-job/src/engine/domain/objects/JobRequest__c/fields/LastExecutionMessage__c.field-meta.xml
<CustomField>
    <fullName>LastExecutionMessage__c</fullName>
    <label>Last Execution Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

apex-job/src/domain/objects/JobRequest__c/fields/LastSelectionDateTime__c.field-meta.xml
<CustomField>
    <fullName>LastSelectionDateTime__c</fullName>
    <label>Last Selection Date Time</label>
    <type>DateTime</type>
</CustomField>

apex-job/src/domain/objects/JobRequest__c/fields/NextExecutionDateTime__c.field-meta.xml
<CustomField>
    <fullName>NextExecutionDateTime__c</fullName>
    <label>Next Execution Date Time</label>
    <type>DateTime</type>
</CustomField>

apex-job/src/engine/domain/objects/JobRequest__c/fields/ProcessingTime__c.field-meta.xml
<CustomField>
    <fullName>ProcessingTime__c</fullName>
    <description>Time spent to process this job in milliseconds, from scheduled time to end</description>
    <label>Processing Time (ms)</label>
    <type>Number</type>
    <precision>18</precision>
    <scale>0</scale>
</CustomField>

apex-job/src/engine/domain/objects/JobRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABORTED</fullName>
                <label>Aborted</label>
            </value>
            <value>
                <fullName>FAILURE</fullName>
                <label>Failure</label>
            </value>
            <value>
                <fullName>KILLED</fullName>
                <label>Killed</label>
            </value>
            <value>
                <fullName>MALFORMED_ARGUMENT</fullName>
                <label>Malformed Argument</label>
            </value>
            <value>
                <fullName>READY</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
                <label>Success</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

apex-job/src/engine/domain/objects/JobRequest__c/fields/UnitRunTime__c.field-meta.xml
<CustomField>
    <fullName>UnitRunTime__c</fullName>
    <description>Deduced Unit Time (based on the chunk size) spent executing this job in milliseconds</description>
    <label>Unit Run Time (derived in ms)</label>
    <type>Number</type>
    <precision>18</precision>
    <scale>0</scale>
</CustomField>

apex-job/src/domain/objects/JobRequest__c/fields/WaitTime__c.field-meta.xml
<CustomField>
    <fullName>WaitTime__c</fullName>
    <description>Time to wait before being selected in milliseconds</description>
    <label>Wait Time (ms)</label>
    <type>Number</type>
    <precision>18</precision>
    <scale>0</scale>
</CustomField>

apex-job/src/monitor/classes/adapter/JobMonitorController.cls
@SuppressWarnings('PMD.ApexCRUDViolation')
public with sharing class JobMonitorController {
  private static final List<String> ALIVE_QUEUEABLE_STATUS = new List<String>{ 'Processing', 'Queued', 'Preparing' };
  private static final String QUEUEABLE_JOB_TYPE = 'Queueable';
  private static final String SCHEDULED_JOB_TYPE = 'ScheduledApex';
  private static final String JOB_NAME = AsyncApexJobExecutor.class.getName();
  private static final String JOB_WATCHER_NAME = ApexJobWatcher.class.getName();
  private static final String CUSTOM_PERMISSION = 'Manage_Async_Job_Engine';

  @AuraEnabled
  public static List<JobRequest__c> getJobRequestPage(final Integer limitSize, final Integer offsetVal) {
    return [
      SELECT
        Id,
        Name,
        JobDescription__c,
        JobDescription__r.ProcessorName__c,
        Status__c,
        Enabled__c,
        IsCandidat__c,
        AttemptNumber__c,
        WaitTime__c,
        ChunkRunTime__c,
        UnitRunTime__c,
        ProcessingTime__c,
        LastSelectionDateTime__c,
        LastExecutionDateTime__c,
        NextExecutionDateTime__c,
        LastExecutionMessage__c,
        Argument__c
      FROM JobRequest__c
      WHERE IsCandidat__c = TRUE
      ORDER BY
        IsDeleted ASC,
        JobDescription__r.Priority__c DESC,
        JobDescription__r.MaxChunkSize__c ASC,
        JobDescription__r.CalloutBaseConsumption__c ASC,
        JobDescription__r.LastExecutionDateTime__c ASC NULLS FIRST,
        NextExecutionDateTime__c ASC
      LIMIT :limitSize
      OFFSET :offsetVal
      ALL ROWS
    ];
  }

  @AuraEnabled
  public static List<Map<String, Object>> getStatusByProcessor() {
    final List<AggregateResult> rows = [
      SELECT
        Count(Id) nbRows,
        Status__c status,
        JobDescription__c processorId,
        MAX(JobDescription__r.MaxChunkSize__c) maxBulk,
        MAX(JobDescription__r.SmallestFailingChunk__c) smallestFailingChunk,
        MAX(JobDescription__r.SuccessStreak__c) successStreak,
        MAX(JobDescription__r.ConsecutiveFailures__c) consecutiveFailure,
        SUM(AttemptNumber__c) nbTry,
        FORMAT(MIN(NextExecutionDateTime__c)) nextExecutionDateTime,
        FORMAT(MIN(LastModifiedDate)) lastExecutionDateTime
      FROM JobRequest__c
      GROUP BY Status__c, JobDescription__c
      ORDER BY Status__c, JobDescription__c
    ];
    final List<Map<String, Object>> out = new List<Map<String, Object>>();
    for (AggregateResult ar : rows) {
      final Map<String, Object> m = ar.getPopulatedFieldsAsMap();
      out.add(m);
    }
    return out;
  }

  @AuraEnabled(cacheable=true)
  public static List<JobDescription__c> getJobDescriptionInfos(final List<Id> jobDescriptionIds) {
    return [SELECT Id, ProcessorName__c FROM JobDescription__c WHERE Id IN :jobDescriptionIds];
  }

  @AuraEnabled
  public static Boolean isEnabled() {
    ApexJobConfig__c cfg = ApexJobConfig__c.getOrgDefaults();
    return cfg?.Enabled__c == true;
  }

  @AuraEnabled
  public static Integer getExecutorCount() {
    final Integer asyncApexJobExecutorCount = [
      SELECT COUNT()
      FROM AsyncApexJob
      WHERE Status IN :ALIVE_QUEUEABLE_STATUS AND JobType = :QUEUEABLE_JOB_TYPE AND ApexClass.Name = :JOB_NAME
    ];
    return asyncApexJobExecutorCount;
  }

  @AuraEnabled
  public static Boolean isRecoveryBatchAlive() {
    final Integer recoveryCount = [
      SELECT COUNT()
      FROM AsyncApexJob
      WHERE Status IN :ALIVE_QUEUEABLE_STATUS AND JobType = :SCHEDULED_JOB_TYPE AND ApexClass.Name = :JOB_WATCHER_NAME
    ];
    return recoveryCount > 0;
  }

  @AuraEnabled
  public static Boolean pauseEngine() {
    assertPerm();
    ApexJobConfig__c cfg = ApexJobConfig__c.getOrgDefaults();
    cfg.Enabled__c = false;
    upsert cfg;
    return !cfg.Enabled__c;
  }

  @AuraEnabled
  public static Boolean resumeEngine() {
    assertPerm();
    ApexJobConfig__c cfg = ApexJobConfig__c.getOrgDefaults();
    cfg.Enabled__c = true;
    upsert cfg;
    return cfg.Enabled__c;
  }

  @AuraEnabled
  public static Id restartEngine() {
    assertPerm();
    final JobExecutorSpawner spawner = new JobExecutorQueueableSpawner();
    return spawner.enqueue(0);
  }

  private static void assertPerm() {
    if (!FeatureManagement.checkPermission(CUSTOM_PERMISSION)) {
      throw new AuthorizationException('Missing permission: ' + CUSTOM_PERMISSION);
    }
  }

  public class AuthorizationException extends Exception {
  }
}